title: IT Auditor Training
description: Dokumen pelatihan IT Auditor
baseurl: "" # Kosongkan jika ini repositori khusus untuk GitHub Pages
theme: minima
markdown: kramdown
navigation:
  - title: Beranda
    url: /
  - title: Daftar Risiko
    url: /risiko
  - title: Kontak
    url: /kontak
